export type CohortType =
  | 'MASTERING_BITCOIN'
  | 'LEARNING_BITCOIN_FROM_COMMAND_LINE'
  | 'PROGRAMMING_BITCOIN'
  | 'BITCOIN_PROTOCOL_DEVELOPMENT';

export type UserRole =
  | 'ADMIN'
  | 'TEACHING_ASSISTANT'
  | 'STUDENT';