export enum CohortType {
  MASTERING_BITCOIN = 'MASTERING_BITCOIN',
  LEARNING_BITCOIN_FROM_COMMAND_LINE = 'LEARNING_BITCOIN_FROM_COMMAND_LINE',
  PROGRAMMING_BITCOIN = 'PROGRAMMING_BITCOIN',
  BITCOIN_PROTOCOL_DEVELOPMENT = 'BITCOIN_PROTOCOL_DEVELOPMENT',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  TEACHING_ASSISTANT = 'TEACHING_ASSISTANT',
  STUDENT = 'STUDENT',
}
